-- Création de la base de données
CREATE DATABASE IF NOT EXISTS vocabulaire_musical;
USE vocabulaire_musical;

-- Création de la table vocabulaire_musical
CREATE TABLE IF NOT EXISTS vocabulaire_musical (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nom VARCHAR(255) NOT NULL,
    definition TEXT NOT NULL,
    image VARCHAR(255),   -- lien ou nom de fichier image
    audio VARCHAR(255)    -- lien ou nom de fichier audio
);

-- Insertion des données
INSERT INTO vocabulaire_musical (nom, definition, image, audio) VALUES
('Latin', 'Langue indo-européenne de l\'Antiquité parlée à Rome et en Italie, à l\'origine des langues romanes modernes et utilisée longtemps comme langue savante en Europe.', NULL, NULL),
('Grec', 'Langue indo-européenne parlée en Grèce antique, connue pour ses grands textes littéraires, philosophiques et scientifiques en grec ancien, ancêtre du grec moderne.', NULL, NULL),
('Langues créoles', 'Langues nées du contact entre plusieurs langues, devenues langues maternelles, souvent issues de situations coloniales, comme le créole haïtien ou le créole réunionnais.', NULL, NULL),
('Langues pidgin', 'Langues simplifiées créées pour permettre la communication entre groupes ne partageant pas de langue commune, généralement utilisées comme langues secondaires.', NULL, NULL),
('Langues signées', 'Langues naturelles utilisant les gestes, expressions faciales et mouvements des mains pour communiquer, comme la langue des signes française (LSF) ou l\'American Sign Language (ASL).', NULL, NULL),
('Langues construites', 'Langues inventées volontairement par des individus ou des groupes pour des buts spécifiques (communication universelle, œuvres de fiction ou musicales), comme l\'espéranto, le Sindarin (langue des Elfes de la Terre du Milieu) ou le Kobaïen du groupe Magma.', NULL, NULL),
('Langues aborigènes', 'Ensemble de centaines de langues parlées traditionnellement par les peuples aborigènes d\'Australie, souvent très variées et appartenant à plusieurs familles distinctes comme le pama-nyungan.', NULL, NULL),
('Langues amérindiennes', 'Ensemble très diversifié de langues parlées par les peuples autochtones des Amériques, comme le quechua, le nahuatl, le guarani et le navajo.', NULL, NULL),
('Langue coréenne', 'Langue parlée en Corée du Sud et du Nord, utilisant l\'alphabet hangul, considérée comme une langue isolée sans parenté clairement établie avec d\'autres familles linguistiques.', NULL, NULL),
('Langue japonaise', 'Langue isolée parlée au Japon, utilisant trois systèmes d\'écriture (hiragana, katakana, kanji) et n\'ayant pas de lien direct confirmé avec d\'autres familles linguistiques.', NULL, NULL),
('Langues sino-tibétaines', 'Grande famille linguistique d\'Asie regroupant le chinois (mandarin, cantonais), le tibétain et le birman.', NULL, NULL),
('Langues dravidiennes', 'Famille de langues du sud de l\'Inde et du Sri Lanka, comprenant le tamoul, le télougou, le kannada et le malayalam.', NULL, NULL),
('Langues ouraliennes', 'Famille de langues d\'Europe du Nord et de Sibérie, dont le finnois, l\'estonien et le hongrois sont les principales représentantes.', NULL, NULL),
('Langues altaïques', 'Groupe hypothétique rassemblant les langues turques, mongoles et toungouses d\'Asie centrale et orientale.', NULL, NULL),
('Langues austroasiatiques', 'Famille de langues d\'Asie du Sud-Est comprenant le vietnamien, le khmer (cambodgien) et plusieurs langues tribales.', NULL, NULL),
('Langues austronésiennes', 'Grande famille de langues parlées des îles du Pacifique jusqu\'à Madagascar, incluant le malais, le tagalog et le maori.', NULL, NULL),
('Langues afro-asiatiques', 'Famille de langues parlées principalement en Afrique du Nord et au Moyen-Orient, incluant l\'arabe, le berbère, et le haoussa.', NULL, NULL),
('Langues nilo-sahariennes', 'Groupe hypothétique de langues parlées autour du Nil et du Sahara central, comprenant le dinka, le kanuri et d\'autres langues minoritaires.', NULL, NULL),
('Langues nigéro-congolaises', 'La plus grande famille de langues africaines en nombre de langues, comprenant le swahili, le yoruba et le zoulou.', NULL, NULL),
('Langues khoïsan', 'Groupe de langues d\'Afrique australe caractérisées par l\'utilisation de clics, parlées par les peuples khoïkhoïs et sans.', NULL, NULL),
('Langues oubanguiennes', 'Sous-groupe de langues nigéro-congolaises parlées principalement en République centrafricaine et ses alentours, incluant le sango.', NULL, NULL),
('Langues mandé', 'Sous-famille de langues nigéro-congolaises parlée en Afrique de l\'Ouest, incluant le bambara, le malinké et le soninké.', NULL, NULL),
('Langues germaniques', 'Groupe de langues indo-européennes apparu en Europe du Nord, comprenant l\'anglais, l\'allemand, le néerlandais et les langues scandinaves.', NULL, NULL),
('Langues romanes', 'Groupe de langues issues du latin vulgaire de l\'Empire romain, incluant le français, l\'espagnol, l\'italien, le portugais et le roumain.', NULL, NULL),
('Langues slaves', 'Famille de langues indo-européennes parlées en Europe de l\'Est et du Nord, comme le russe, le polonais, le tchèque et le serbe.', NULL, NULL),
('Langues finno-ougriennes', 'Groupe de langues non indo-européennes d\'Europe du Nord et de l\'Oural, comprenant le finnois, l\'estonien et le hongrois.', NULL, NULL),
('Langues celtiques', 'Anciennes langues indo-européennes parlées historiquement en Europe de l\'Ouest, dont le breton, le gaélique irlandais et le gallois.', NULL, NULL),
('Langue basque', 'Langue isolée, sans lien connu avec d\'autres familles, parlée au Pays basque entre la France et l\'Espagne.', NULL, NULL),
('Musique occidentale de tradition écrite', 'Style musical savant européen caractérisé par son système de notation et son évolution historique à travers les périodes stylistiques majeures.', NULL, NULL),
('Musique du Moyen-Âge', 'Style (Ve-XVe siècles) marqué par le chant grégorien, l\'organum, les troubadours et l\'émergence de la polyphonie. Instruments typiques : vièle, harpe, flûte à bec.', NULL, NULL),
('Musique de la Renaissance', 'Style (XVe-XVIe siècles) caractérisé par la polyphonie vocale complexe et le développement des instruments comme le luth et le clavecin.', NULL, NULL),
('Style baroque', 'Style (1600-1750) marqué par la basse continue, l\'opéra, les formes concertantes et les grands maîtres comme Bach et Haendel.', NULL, NULL),
('Style classique', 'Style (1750-1800) caractérisé par la clarté formelle, l\'équilibre et les compositeurs comme Mozart et Haydn.', NULL, NULL),
('Style romantique', 'Style (1800-1900) privilégiant l\'expression des émotions, les formes libres et les grands virtuoses comme Chopin et Liszt.', NULL, NULL),
('Musique moderne', 'Style (début XXe siècle) marqué par la rupture avec le système tonal et l\'émergence de nouvelles techniques compositionnelles.', NULL, NULL),
('Musique contemporaine', 'Style actuel (après 1945) explorant des approches innovantes comme la musique concrète ou minimaliste.', NULL, NULL),
('Musiques traditionnelles / folk', 'Style musical transmis oralement, propre à une culture ou région, utilisant souvent des instruments locaux caractéristiques.', NULL, NULL),
('Musique celtique', 'Style musical des pays celtes utilisant harpe, cornemuse et violon, avec des mélodies caractéristiques.', NULL, NULL),
('Flamenco', 'Style andalou associant chant passionné, danse expressive et guitare rythmique.', NULL, NULL),
('Fado', 'Style chanté portugais exprimant la nostalgie, accompagné de la guitare portugaise.', NULL, NULL),
('Gnawa', 'Style marocain aux rythmes hypnotiques, mêlant traditions africaines et soufies.', NULL, NULL),
('Blues traditionnel', 'Style afro-américain né dans le Delta du Mississippi, basé sur des structures simples et une expressivité vocale intense.', NULL, NULL),
('Musique africaine', 'Style diversifié caractérisé par des polyphonies et des polyrythmies complexes.', NULL, NULL),
('Musiques populaires modernes', 'Styles musicaux apparus principalement au XXe siècle, caractérisés par :\n1. Une large diffusion médiatique (radio, disques, streaming)\n2. Une production souvent industrielle\n3. Une forte association avec la culture de masse\n4. L\'utilisation d\'instruments amplifiés/électroniques\n\nPrincipales caractéristiques :\n- Structures souvent simples et répétitives\n- Importance du rythme et de la mélodie\n- Forte connexion avec les mouvements sociaux et générationnels\n- Évolution rapide influencée par la technologie.', NULL, NULL),
('Jazz', 'Style musical né aux États-Unis combinant improvisation, syncopes et harmonies sophistiquées.', NULL, NULL),
('Rock', 'Style apparu dans les années 1950 centré sur les guitares électriques et une énergie rythmique puissante.', NULL, NULL),
('Reggae', 'Style jamaïcain au tempo modéré, marqué par l\'accentuation du contretemps et des textes engagés.', NULL, NULL),
('Rap', 'Style vocal parlé-rythmé, utilisant à l\'origine des samples en boucle comme accompagnement, élément central de la culture hip-hop.', NULL, NULL),
('Musiques du monde', 'Catégorie regroupant les traditions musicales non-occidentales et les fusions interculturelles, caractérisées par : une transmission souvent orale ou maître-élève, l\'utilisation d\'instruments traditionnels spécifiques, des systèmes musicaux différents de la théorie occidentale (échelles, rythmes), des fonctions sociales/cérémonielles importantes.', NULL, NULL),
('Samba', 'Style brésilien énergique associé au carnaval, basé sur des percussions complexes.', NULL, NULL),
('Raga', 'Style mélodique de la musique indienne lié à des moments précis et des émotions spécifiques.', NULL, NULL),
('Musique arabo-andalouse', 'Style résultant d\'un métissage entre musique arabe venue de l\'Orient, musique afro-berbère du Maghreb et musique pratiquée dans la Péninsule Ibérique avant le VIIIe siècle, utilisant des modes spécifiques.', NULL, NULL),
('Chants pygmées', 'Style vocal africain caractérisé par des polyphonies complexes et l\'utilisation du yodel.', NULL, NULL),
('Musiques rituelles ou spirituelles', 'Pratiques musicales sacrées ou cérémonielles remplissant une fonction médiatrice entre le profane et le sacré. Elles ont pour vocation d\'établir une communication avec les entités spirituelles (invocations, prières chantées), de faciliter les transitions ritualisées (rites de passage, cycles calendaires), de transmettre des connaissances religieuses par la mise en musique des textes sacrés, d\'induire des états de conscience modifiés (transe, extase, méditation).', NULL, NULL),
('Chamanisme', 'Style musical utilisé dans les pratiques spirituelles pour induire des états de transe.', NULL, NULL),
('Gospel', 'Style religieux afro-américain marqué par son intensité émotionnelle et ses harmonies vocales riches.', NULL, NULL),
('Qawwali', 'Style soufi visant à provoquer l\'extase mystique par la répétition rythmique et mélodique.', NULL, NULL),
('Musique de tradition orale', 'Style transmis sans support écrit, par imitation et mémoire collective.', NULL, NULL),
('Musique de tradition écrite', 'Pratique musicale fondée sur un système de notation précis permettant la fixation et la transmission des œuvres.', NULL, NULL),
('Musique savante', 'Style composé et noté, relevant d\'une démarche artistique élaborée.', NULL, NULL),
('Musique populaire', 'Musique transmise principalement par voie orale au sein d\'une communauté, associée à des pratiques collectives et quotidiennes, se distinguant de la musique savante par son mode de transmission et son ancrage dans une culture.', NULL, NULL),
('Cas hybrides', 'Pratiques musicales combinant des éléments de transmission orale et écrite, créant un continuum entre culture savante et populaire. Ces formes émergent lorsque des traditions orales sont notées, lorsque des musiques écrites intègrent des pratiques improvisées, ou lorsque des musiciens formés à l\'écrit revisitent des répertoires traditionnels. Exemples typiques : le jazz (improvisation orale sur structures harmoniques écrites), le flamenco (phrases mélodiques transmises oralement mais styles codifiés par écrit), ou certaines musiques baroques (partitions écrites avec ornementation improvisée).', NULL, NULL),
('Violon', 'Instrument à cordes frottées, le plus petit et aigu de sa famille. Joué avec un archet ou en pizzicato.', 'images/violon.jpg', 'audio/violon.mp3'),
('Violon alto', 'Instrument à cordes frottées, légèrement plus grand que le violon, avec un son plus chaud et grave.', 'images/alto.jpg', 'audio/alto.mp3'),
('Violoncelle', 'Instrument à cordes frottées joué assis, tenu entre les jambes. Tessiture entre l\'alto et la contrebasse.', 'images/violoncelle.jpg', 'audio/violoncelle.mp3'),
('Contrebasse', 'Le plus grand et le plus grave des instruments à cordes frottées, utilisé en classique et en jazz.', 'images/contrebasse.jpg', 'audio/contrebasse.mp3'),
('Archet', 'Baguette en bois avec crins de cheval tendus, utilisée pour frotter les cordes des instruments.', 'images/archet.jpg', 'audio/archet.mp3'),
('Guitare', 'Instrument à cordes pincées, avec caisse de résonance et manche fretté. Existe en versions classique, folk et électrique.', 'images/guitare.jpg', 'audio/guitare.mp3'),
('Harpe', 'Grand instrument à cordes pincées, joué verticalement. Utilisé en musique classique et celtique.', 'images/harpe.jpg', 'audio/harpe.mp3'),
('Clavecin', 'Instrument à clavier et cordes pincées, très utilisé à l\'époque baroque.', 'images/clavecin.jpg', 'audio/clavecin.mp3'),
('Guitare électrique', 'Guitare sans caisse de résonance, nécessitant un amplificateur. Utilisée en rock, blues et jazz.', 'images/guitare-electrique.jpg', 'audio/guitare-electrique.mp3'),
('Basse électrique', 'Version grave de la guitare électrique, souvent à 4 cordes. Essentielle dans les groupes modernes.', 'images/basse-electrique.jpg', 'audio/basse-electrique.mp3'),
('Piano', 'Instrument à clavier où les cordes sont frappées par des marteaux. Existe en versions acoustique et numérique.', 'images/piano.jpg', 'audio/piano.mp3'),
('Flûte traversière', 'Instrument à vent en métal (originellement en bois), sans anche. Son clair et brillant.', 'images/flute-traversiere.jpg', 'audio/flute-traversiere.mp3'),
('Flûte à bec', 'Petite flûte droite avec un bec, souvent utilisée pour l\'apprentissage musical.', 'images/flute-a-bec.jpg', 'audio/flute-a-bec.mp3'),
('Clarinette', 'Instrument à anche simple, au son chaud et expressif. Utilisée en classique et jazz.', 'images/clarinette.jpg', 'audio/clarinette.mp3'),
('Cor de basset', 'Variété de clarinette alto, plus grave, utilisée notamment par Mozart.', 'images/cor-de-basset.jpg', 'audio/cor-de-basset.mp3'),
('Saxophone', 'Instrument en métal à anche simple, inventé par Adolphe Sax. Très présent en jazz.', 'images/saxophone.jpg', 'audio/saxophone.mp3'),
('Trompette', 'Instrument à vent aigu, à pistons. Son brillant et puissant.', 'images/trompette.jpg', 'audio/trompette.mp3'),
('Cor', 'Instrument à vent avec large pavillon, son chaud et rond. Utilisé en orchestre.', 'images/cor.jpg', 'audio/cor.mp3'),
('Trombone', 'Instrument à coulisse, permettant des glissandos. Son puissant et noble.', 'images/trombone.jpg', 'audio/trombone.mp3'),
('Tuba', 'Le plus grave des cuivres, avec un son profond et rond.', 'images/tuba.jpg', 'audio/tuba.mp3'),
('Percussions', 'Famille d\'instruments dont le son est produit en frappant, secouant ou grattant.', 'images/percussions.jpg', 'audio/percussions.mp3'),
('percussions à peau', 'Percussions dont le son est produit par la vibration d\'une membrane tendue.', 'images/percussions-peau.jpg', 'audio/percussions-peau.mp3'),
('percussions en bois', 'Percussions faites en bois.', 'images/percussions-bois.jpg', 'audio/percussions-bois.mp3'),
('percussions métalliques', 'Percussions faites en métal, comme les cymbales ou le triangle.', 'images/percussions-metal.jpg', 'audio/percussions-metal.mp3'),
('batterie', 'Ensemble de percussions (toms, cymbales, grosse caisse) joué avec des baguettes.', 'images/batterie.jpg', 'audio/batterie.mp3'),
('caisse claire', 'Tambour avec timbre (fil métallique vibrant), utilisé en orchestre et batterie.', 'images/caisse-claire.jpg', 'audio/caisse-claire.mp3'),
('grosse caisse', 'Tambour très grave, utilisé pour marquer les temps forts.', 'images/grosse-caisse.jpg', 'audio/grosse-caisse.mp3'),
('tom', 'Tambour sans timbre, de différentes tailles, composant de la batterie.', 'images/tom.jpg', 'audio/tom.mp3'),
('cymbales', 'Disques métalliques frappés ou entrechoqués pour produire un son vibrant.', 'images/cymbales.jpg', 'audio/cymbales.mp3'),
('charlestone', 'Paire de cymbales actionnée par une pédale, composant de la batterie.', 'images/charlestone.jpg', 'audio/charlestone.mp3'),
('tambourin', 'Petit cadre avec des cymbalettes ou une peau, secoué ou frappé.', 'images/tambourin.jpg', 'audio/tambourin.mp3'),
('triangle', 'Tige métallique en forme de triangle, frappée avec une baguette.', 'images/triangle.jpg', 'audio/triangle.mp3'),
('woodblock', 'Bloc de bois creux frappé avec une baguette, son sec et percussif.', 'images/woodblock.jpg', 'audio/woodblock.mp3'),
('claves', 'Bâtons de bois dur entrechoqués pour produire un son claquant.', 'images/claves.jpg', 'audio/claves.mp3'),
('guiro', 'Instrument à rainures frottées avec une baguette, son gratté caractéristique.', 'images/guiro.jpg', 'audio/guiro.mp3'),
('congas', 'Tambours cubains hauts et étroits, joués à mains nues.', 'images/congas.jpg', 'audio/congas.mp3'),
('bongos', 'Petits tambours jumelés, d\'origine cubaine, joués avec les doigts.', 'images/bongos.jpg', 'audio/bongos.mp3'),
('djembe', 'Tambour africain en forme de calice, joué à mains nues.', 'images/djembe.jpg', 'audio/djembe.mp3'),
('timbales latines', 'Petits tambours à peau fine, utilisés dans la musique latine.', 'images/timbales-latines.jpg', 'audio/timbales-latines.mp3'),
('shaker', 'Petit instrument secoué, rempli de granulés pour produire un son continu.', 'images/shaker.jpg', 'audio/shaker.mp3'),
('maracas', 'Instrument de percussion secoué, constitué d\'une sphère creuse remplie de graines.', 'images/maracas.jpg', 'audio/maracas.mp3'),
('tambour de basque', 'Cadre circulaire avec une peau et des cymbalettes, joué en le secouant ou en frappant la peau.', 'images/tambour-basque.jpg', 'audio/tambour-basque.mp3'),
('tam-tam', 'Grand disque métallique suspendu, sans note définie, produisant un son complexe et étalé.', 'images/tam-tam.jpg', 'audio/tam-tam.mp3'),
('timbales', 'Tambours accordables, utilisés en orchestre pour des notes précises.', 'images/timbales.jpg', 'audio/timbales.mp3'),
('xylophone', 'Instrument à lames de bois frappées, son sec et clair.', 'images/xylophone.jpg', 'audio/xylophone.mp3'),
('marimba', 'Cousin grave du xylophone, avec des lames en bois et des résonateurs.', 'images/marimba.jpg', 'audio/marimba.mp3'),
('vibraphone', 'Instrument à lames métalliques avec motorisation pour un effet vibrato.', 'images/vibraphone.jpg', 'audio/vibraphone.mp3'),
('glockenspiel', 'Petit instrument à lames métalliques, son cristallin et aigu.', 'images/glockenspiel.jpg', 'audio/glockenspiel.mp3'),
('cloches tubulaires', 'Série de tubes métalliques accordés, frappés avec un maillet.', 'images/cloches-tubulaires.jpg', 'audio/cloches-tubulaires.mp3'),
('célesta', 'Instrument à clavier et lames métalliques, son proche du carillon.', 'images/celesta.jpg', 'audio/celesta.mp3'),
('gong', 'Grand disque métallique suspendu, frappé pour produire un son à hauteur déterminée profond et résonnant.', 'images/gong.jpg', 'audio/gong.mp3'),
('bois', 'Famille d\'instruments à vent traditionnellement en bois (flûtes, clarinettes, etc.).', 'images/bois.jpg', 'audio/bois.mp3'),
('cuivres', 'Famille d\'instruments à vent en métal, où le son est produit par la vibration des lèvres (trompette, trombone, etc.).', 'images/cuivres.jpg', 'audio/cuivres.mp3'),
('soprano colorature', 'Type de soprano avec un large ambitus et une grande agilité vocale.', NULL, 'audio/soprano-colorature.mp3'),
('soprano', 'Registre le plus aigu des voix féminines.', 'images/soprano.jpg', 'audio/soprano.mp3'),
('mezzo-soprano', 'Registre moyen des voix féminines.', 'images/mezzo-soprano.jpg', 'audio/mezzo-soprano.mp3'),
('alto', 'Registre le plus grave des voix féminines, dans le cadre d\'une ensemble vocal.', NULL, NULL),
('contralto', 'Registre le plus grave des voix féminines solistes.', NULL, NULL),
('haute-contre', 'Ténor qui utilise sa voix de tête pour certains aigus ou ténor léger.', NULL, 'audio/contretenor.mp3'),
('contreténor', 'Chanteur utilisant sa voix de tête, produisant une tessiture similaire à celle d\'une soprano.', 'images/contretenor.jpg', 'audio/contretenor.mp3'),
('ténor', 'Registre le plus aigu des voix masculines.', 'images/tenor.jpg', 'audio/tenor.mp3'),
('baryton', 'Registre moyen des voix masculines.', 'images/baryton.jpg', 'audio/baryton.mp3'),
('basse', 'Registre le plus grave des voix masculines.', 'images/basse.jpg', 'audio/basse.mp3'),
('basse profonde', 'Basse avec une tessiture très grave, capable de produire des sons très bas.', NULL, 'audio/basse-profonde.mp3'),
('aigu', 'Un registre vocal élevé, souvent utilisé pour désigner des sons de haute fréquence, comme ceux produits par un soprano.', NULL, NULL),
('médium', 'Le registre vocal intermédiaire, ni trop aigu, ni trop grave. Il est souvent utilisé par des voix comme les mezzo-sopranos.', NULL, NULL),
('grave', 'Un registre vocal grave, souvent utilisé par des voix de basse ou des voix masculines plus profondes.', NULL, NULL),
('ambitus', 'Étendue des notes qu\'un chanteur peut produire, du plus grave au plus aigu.', NULL, NULL),
('tessiture', 'Étendue des notes qu\'un chanteur peut produire confortablement, du plus grave au plus aigu.', NULL, NULL),
('registre', 'Partie de tessiture d’une voix avec les mêmes caractéristiques sonores.', NULL, NULL),
('registre naturel', 'Ou registre de poitrine, ou voix de poitrine, utilisé principalement par les hommes.', NULL, NULL),
('registre aigu', 'Ou voix de fausset ou falsetto (utilisé par les contreténors), ou voix de tête (pour les voix féminines).', NULL, NULL),
('voix mixte', 'Registre intermédiaire, permet d’éviter la coupure entre les registres graves et aigus.', NULL, NULL),
('abdomen', 'Partie inférieure du tronc, impliquée dans la respiration abdominale, technique importante pour le soutien vocal.', NULL, NULL),
('bronches', 'Voies aériennes principales menant aux poumons.', NULL, NULL),
('cavités de résonance', 'Espaces au-dessus du larynx, incluant la gorge et la bouche, qui sont utilisés pour la résonance vocale et modulent le son produit.', NULL, NULL),
('cordes vocales', 'Muscles tendus dans le larynx qui vibrent pour produire des sons lorsqu\'ils sont comprimées par l\'air provenant des poumons.', 'images/cordes-vocales.jpg', 'audio/cordes-vocales.mp3'),
('côtes', 'Os qui protègent les organes vitaux dans la poitrine, dont le rôle est important dans la respiration.', NULL, NULL),
('diaphragme', 'Muscle principal utilisé dans la respiration, situé sous les poumons, qui permet d\'inhaler et d\'exhaler et dont le contrôle est important dans le chant.', 'images/diaphragme.jpg', 'audio/diaphragme.mp3'),
('résonateurs', 'Cavités (bouche, gorge, nez, sinus) permettant l\'amplification et la modulation des sons produits par les cordes vocales, donnant ainsi à la voix son timbre unique.', NULL, NULL),
('fosses nasales', 'Passages dans le nez par lesquels l\'air est inhalé avant de passer dans les poumons, et qui contribuent à la résonance du son vocal.', NULL, NULL),
('glotte', 'Espace entre les cordes vocales dans le larynx, par lequel l\'air passe pour produire des sons.', NULL, NULL),
('larynx', 'Organe situé dans la gorge qui contient les cordes vocales. Il est crucial dans la production de la voix.', 'images/larynx.jpg', 'audio/larynx.mp3'),
('oreille', 'L\'organe de l\'audition qui permet de percevoir les sons et de maintenir un contrôle précis de la hauteur et de la justesse de la voix.', NULL, NULL),
('pharynx', 'La zone derrière la bouche et le nez qui mène à l\'œsophage et aux voies respiratoires. Il joue un rôle dans la résonance vocale.', NULL, NULL),
('poumons', 'Organes responsables de l\'échange de gaz (oxygène et dioxyde de carbone).', 'images/poumons.jpg', 'audio/poumons.mp3'),
('physiologie', 'La science qui étudie le fonctionnement des systèmes du corps humain, y compris la respiration et la production vocale.', NULL, NULL),
('sternum', 'Os du thorax auquel les côtes sont attachées. Il protège le cœur et les poumons et est un point de référence pour la respiration.', NULL, NULL),
('thorax', 'Partie du tronc qui contient les poumons et le cœur.', NULL, NULL),
('trachée', 'Tube qui mène de la gorge aux poumons, permettant le passage de l\'air pour la respiration et la production vocale.', NULL, NULL),
('voies aériennes', 'Passages par lesquels l\'air entre et sort des poumons, incluant la trachée et les bronches.', NULL, NULL),
('voile du palais', 'Partie postérieure du palais qui peut être levée pour fermer ou ouvrir les cavités nasales, affectant la résonance du son.', NULL, NULL),
('a cappella', 'Chanter sans accompagnement instrumental.', NULL, NULL),
('décomposition du son', 'Façon dont un son vocal est formé par la vibration des cordes vocales et modulé par les cavités de résonance.', NULL, NULL),
('intonation', 'Manière dont les variations de hauteur et de tonalité sont utilisées pour exprimer des émotions ou des significations.', NULL, NULL),
('mélisme', 'Art de chanter plusieurs notes sur une seule syllabe, souvent utilisé dans les chants classiques et la musique religieuse.', NULL, NULL),
('onomatopées', 'Mots qui imitent le son qu\'ils représentent (buzz, clang...).', NULL, NULL),
('phénomène vibratoire', 'Processus par lequel les cordes vocales vibrent pour produire du son. La fréquence de cette vibration détermine la hauteur du son.', NULL, NULL),
('résonance', 'Effet de modulation et d\'amplification du son émis par les cordes vocales, produit par les résonateurs.', NULL, NULL),
('soutien', 'Engagement de la respiration abdominale et du diaphragme pour maintenir la constance du son.', NULL, NULL),
('terminaison du son', 'Manière dont un chanteur contrôle l\'extinction d\'une note ou d\'une phrase musicale.', NULL, NULL),
('timbre', 'Qualité ou \'couleur\' de la voix, qui permet de la distinguer d\'une autre, même si elles chantent la même note.', NULL, NULL),
('voile', 'La partie postérieure du palais qui peut être levée pour fermer ou ouvrir les cavités nasales, affectant la résonance du son vocal.', NULL, NULL),
('attaque du son', 'Moment et manière dont un chanteur initie un son ; cela peut influencer la qualité, la précision et le caractère de la voix. L\'attaque du son peut être : \n- douce (ou légère) : les cordes vocales commencent à vibrer avant que l\'air ne soit pleinement expulsé, ce qui produit un son fluide et doux ; souvent utilisé pour un effet plus délicat ou lyrique.\n- dure (ou coup de glotte) : les cordes vocales se ferment fermement avant de s\'ouvrir brusquement sous la pression de l\'air, produisant un son net et précis ; utile pour des effets dramatiques.\n- équilibrée : l\'air et les cordes vocales se synchronisent de manière optimale pour un son clair et soutenu sans tension excessive.', NULL, NULL),
('vocalise', 'Exercice vocal consistant à chanter des notes sur des voyelles sans paroles, utilisé pour échauffer la voix.', NULL, NULL),
('échauffement', 'Exercices effectués pour préparer la voix.', NULL, NULL),
('gestion du souffle', 'Maîtrise et optimisation de l\'utilisation de l\'air pendant l\'émission vocale. Elle est essentielle pour produire un son stable, puissant et contrôlé, tout en évitant la fatigue vocale.', NULL, NULL),
('inspiration', 'Processus de prise de l\'air dans les poumons.', NULL, NULL),
('expiration', 'Processus d\'expulsion de l\'air contenu dans les poumons.', NULL, NULL),
('physiologie', 'Science qui étudie le fonctionnement des systèmes du corps humain, y compris la respiration et la production vocale.', NULL, NULL),
('forme à thèmes', 'Basée sur le développement et la variation de thèmes mélodiques.', NULL, NULL),
('forme bipartite', 'Deux sections distinctes, souvent notées A et B.', NULL, NULL),
('forme continue', 'Forme dans laquelle aucune section n\'est clairement définie.', NULL, NULL),
('forme ouverte', 'Sans section clairement délimitée, elle permet une grande liberté dans l\'organisation des idées musicales et l\'improvisation. Fréquente en musique contemporaine, où l\'interprète ou le compositeur ont une grande marge de manœuvre.', NULL, NULL),
('forme par argument', 'Basée sur le développement logique d\'idées thématiques.', NULL, NULL),
('forme strophique', 'Chaque strophe de texte est chantée sur la même mélodie.', NULL, NULL),
('break', 'Section d\'une composition où un instrument ou un groupe joue seul.', NULL, NULL),
('cellule', 'Petit motif musical répété ou développé.', NULL, NULL),
('citation', 'Extrait musical préexistant dans une nouvelle composition ; pour créer un effet de reconnaissance ou d’hommage.', NULL, NULL),
('couplet', 'Section qui alterne avec le refrain.', NULL, NULL),
('développement', 'Section où les thèmes sont transformés, combinés ou explorés.', NULL, NULL),
('élément', 'Composant de base, comme une mélodie, un rythme, une harmonie ou un timbre.', NULL, NULL),
('exposition', 'Première section, dans laquelle les thèmes principaux sont présentés.', NULL, NULL),
('partie', 'Section souvent définie par son caractère ou sa fonction ; par exemple, les parties d’une chanson (couplet, refrain, pont).', NULL, NULL),
('phrase', 'Unité mélodique ou harmonique complète qui forme une idée musicale.', NULL, NULL),
('refrain', 'Section répétée, avec les mêmes paroles et mélodie.', NULL, NULL),
('strophe', 'Une section d’une chanson où les paroles changent, mais la musique reste la même.', NULL, NULL),
('ABA', 'Forme musicale en trois parties : une première section (A), une section contrastée (B), puis un retour à la première section (A).', NULL, NULL),
('antienne', 'Court chant liturgique, souvent répété avant et après un psaume.', NULL, NULL),
('cyclique', 'Forme où des thèmes ou motifs réapparaissent tout au long d\'une œuvre, créant une unité.', NULL, NULL),
('da capo', 'Indication pour répéter une section depuis le début (littéralement "depuis le début").', NULL, NULL),
('fugue', 'Forme contrapuntique où un thème (sujet) est introduit puis repris par différentes voix ou instruments. Typique de la musique baroque.', NULL, NULL),
('ground / chaconne / passacaille', 'Formes basées sur une basse répétée.', NULL, NULL),
('marche', 'Composition au rythme régulier, souvent utilisée pour accompagner des défilés.', NULL, NULL),
('petit rondo (ABA C ABA)', 'Variante du rondo.', NULL, NULL),
('reprise', 'Retour d’une section musicale après une autre partie.', NULL, NULL),
('rondeau', 'Forme avec alternance entre refrain et couplets ; en musique française instrumentale et vocale, des périodes médiévale à baroque.', NULL, NULL),
('rondo', 'Comme le rondeau ; souvent utilisé pour les mouvements vifs et joyeux, dans la sonate et la symphonie comme pièce finale.', NULL, NULL),
('thème et variations', 'Structure où le thème initial est suivi de plusieurs variations (mélodie, rythme, harmonie, etc.).', NULL, NULL),
('variation', 'Transformation de certains aspects d’un thème (mélodie, rythme, harmonie, texture, etc.), tout en gardant des éléments reconnaissables avec l’idée originale.', NULL, NULL),
('basse obstinée', 'Ligne de basse répétée tout au long d\'une composition, servant de fondation harmonique.', NULL, NULL),
('boucle', 'Motif répété ; dans les musiques modernes.', NULL, NULL),
('leitmotiv', 'Thème récurrent associé à un personnage, une idée ou une émotion dans une œuvre.', NULL, NULL),
('motif', 'Court élément mélodique ou rythmique répété ou développé dans une composition.', NULL, NULL),
('ostinato mélodique, rythmique ou mélodico-rythmique', 'Motif répété tout au long d\'une composition.', NULL, NULL),
('récurrence', 'Retour répété d’un élément musical (thème, motif, harmonie). Crée une cohésion dans une œuvre.', NULL, NULL),
('répétition', 'Réutilisation d’une section ou d’un motif musical.', NULL, NULL),
('sample', 'Extrait sonore préenregistré, réutilisé dans une nouvelle composition.', NULL, NULL),
('sujet', 'Thème principal d\'une œuvre contrapuntique, notamment d\'une fugue.', NULL, NULL),
('contraste', 'Élément opposé (dynamique, tempo, texture) pour créer de la variété.', NULL, NULL),
('dialogue', 'Interaction musicale entre deux voix ou instruments, on parle souvent de "question-réponse".', NULL, NULL),
('échelle', 'Série de notes ascendantes ou descendantes, souvent utilisée comme base pour une mélodie ou une improvisation.', NULL, NULL),
('lamento', 'Pièce musicale exprimant la tristesse ou le deuil, souvent basée sur une basse descendante.', NULL, NULL),
('mouvement', 'Section autonome d\'une œuvre plus large, comme une symphonie ou une sonate.', NULL, NULL),
('programme', 'Idée extra-musicale, poème ou histoire, qui sert de fil conducteur à une composition.', NULL, NULL),
('réponse', 'Dans le cadre d\'une fugue, la réponse est la version du sujet après qu\'il ait été présenté une première fois. Elle est souvent transposée et modifiée pour s’adapter à la tonalité du passage. Souvent transposée à une quarte ou une quinte.', NULL, NULL),
('rupture', 'Changement soudain ou marqué dans une œuvre musicale, au niveau du tempo, de la tonalité, de la texture ou du style.', NULL, NULL),
('scherzo', 'Composition sans forme fixe, autonome ou mouvement d\'une sonate, d\'une symphonie, etc. ; caractère vif et brillant.', NULL, NULL),
('ternaire (ABA)', 'Structure musicale en trois parties.', NULL, NULL),
('canon', 'Forme contrapuntique où une mélodie est imitée par une ou plusieurs voix à intervalles réguliers.', NULL, NULL),
('canzone', 'Souvent de style léger et mélodique.', NULL, NULL),
('chaconne', 'Forme basée sur la répétition d\'une progression harmonique ou d\'un motif de basse.', NULL, NULL),
('contre-sujet', 'Mélodie secondaire dans une fugue, jouée en contrepoint avec le sujet principal.', NULL, NULL),
('contrepoint', 'Technique musicale où plusieurs mélodies indépendantes sont combinées harmonieusement.', NULL, NULL),
('développement', 'Le développement est une section où le sujet et les contre-sujets sont transformés, fragmentés, combinés ou explorés de manière créative. Après l’exposition (où toutes les voix ont présenté le sujet et la réponse), le développement explore les possibilités du matériel thématique. Il peut inclure des modulations (changements de tonalité), des strettes (entrées rapprochées du sujet) ou des inversions (le sujet joué à l’envers) et prépare le retour à la tonalité principale pour la conclusion.', NULL, NULL),
('fantaisie', 'Forme libre, souvent improvisée, sans structure prédéfinie.', NULL, NULL),
('fugato', 'Passage d\'une composition qui imite le style d\'une fugue sans en être une.', NULL, NULL),
('fuguette', 'Petite fugue, souvent moins complexe qu\'une fugue complète.', NULL, NULL),
('fughetta', 'Petite fugue, souvent moins développée qu\'une fugue complète.', NULL, NULL),
('imitation', 'Technique contrapuntique où une voix ou un instrument reprend un motif ou un thème (sujet) déjà exposé par une autre voix, souvent à un intervalle différent (généralement quarte ou quinte). Cela crée un dialogue entre les voix, tout en maintenant une cohésion thématique. L\'imitation est dite réelle quand la transposition est exacte, tonale quand la réponse est légèrement modifiée pour rester dans la tonalité principale.', NULL, NULL),
('motet', 'Composition vocale polyphonique a cappella, souvent religieuse.', NULL, NULL),
('réponse / comes', 'Imitation du sujet dans une autre voix, souvent transposée.', NULL, NULL),
('ricercare', 'Forme contrapuntique ancienne, précurseur de la fugue.', NULL, NULL),
('sujet / thème / dux', 'Thème principal d\'une fugue, exposé au début et développé tout au long de la composition.', NULL, NULL),
('air', 'Mélodie principale ou section mélodique dans une composition, souvent chantée.', NULL, NULL),
('aléatoire', 'Certains éléments sont laissés au hasard ou à l\'interprétation de l\'exécutant.', NULL, NULL),
('aria', 'Pièce vocale soliste dans un opéra ou une cantate, souvent de forme ABA.', NULL, NULL),
('contraste', 'Élément opposé (dynamique, tempo, texture) pour créer de la variété.', NULL, NULL),
('dialogue', 'Interaction musicale entre deux voix ou instruments, on parle souvent de "question-réponse".', NULL, NULL),
('échelle', 'Série de notes ascendantes ou descendantes, souvent utilisée comme base pour une mélodie ou une improvisation.', NULL, NULL),
('lamento', 'Pièce musicale exprimant la tristesse ou le deuil, souvent basée sur une basse descendante.', NULL, NULL),
('mouvement', 'Section autonome d\'une œuvre plus large, comme une symphonie ou une sonate.', NULL, NULL),
('programme', 'Idée extra-musicale, poème ou histoire, qui sert de fil conducteur à une composition.', NULL, NULL),
('réponse', 'Dans le cadre d\'une fugue, la réponse est la version du sujet après qu\'il ait été présenté une première fois. Elle est souvent transposée et modifiée pour s’adapter à la tonalité du passage. Souvent transposée à une quarte ou une quinte.', NULL, NULL),
('rupture', 'Changement soudain ou marqué dans une œuvre musicale, au niveau du tempo, de la tonalité, de la texture ou du style.', NULL, NULL),
('scherzo', 'Composition sans forme fixe, autonome ou mouvement d\'une sonate, d\'une symphonie, etc. ; caractère vif et brillant.', NULL, NULL),
('ternaire', 'Structure musicale en trois parties. Exemple : ABA', NULL, NULL),
('grille', 'En jazz, séquence d\'accords répétée qui sert de base à l\'improvisation.', NULL, NULL),
('improvisation', 'Art, action de composer et d\'exécuter simultanément.', NULL, NULL),
('sarabande', 'Danse noble et grave, à trois temps (3/4 ou 3/2), de forme binaire, dont chaque phase débutait sur un temps fort, qui se dansait par couples et qui fut introduite à la cour de France au XVIIe siècle. Au XVIIIe, elle est un des éléments fondamentaux de la suite classique située entre la courante et la gigue.', NULL, NULL),
('gavotte', 'Danse française, à deux temps, d\'origine populaire, très en vogue aux dix-septième et dix-huitième siècles.', NULL, NULL),
('timbre', 'Caractéristique d\'un son qui permet de distinguer deux sons de même hauteur et intensité, mais produits par des sources différentes.', NULL, NULL),
('timbre instrumental', 'Qualité sonore propre à chaque instrument, déterminée par sa construction et sa manière d\'être joué.', NULL, NULL),
('timbre vocal', 'Caractéristique unique de la voix d\'une personne, influencée par des facteurs physiologiques.', NULL, NULL),
('couleur', 'Terme souvent utilisé pour décrire le timbre d\'un son ou d\'une musique, en référence à sa richesse et ses nuances.', NULL, NULL),
('texture', 'Manière dont les éléments musicaux (mélodie, harmonie, rythme) sont tissés ensemble pour créer une "trame" sonore.', NULL, NULL),
('spectre sonore', 'Ensemble des fréquences (fondamentale et harmoniques) qui caractérisent un son.', NULL, NULL),
('harmoniques', 'Fréquences multiples de la fréquence fondamentale, qui enrichissent le timbre d\'un son.', NULL, NULL),
('densité', 'Quantité d\'éléments sonores présents dans une texture musicale.', NULL, NULL),
('fondamental', 'Fréquence la plus basse d\'un son, qui détermine sa hauteur perçue.', NULL, NULL),
('formant', 'Renforcement de certaines fréquences dans le spectre sonore, influençant le timbre.', NULL, NULL),
('enveloppe du son', 'Description de l\'évolution d\'un son dans le temps, divisée en attaque, decay, sustain et release.', NULL, NULL),
('enveloppe sonore', 'Façon dont un son évolue dans le temps, influençant sa perception.', NULL, NULL),
('bruit', 'Son complexe et non périodique, souvent perçu comme désagréable.', NULL, NULL),
('résonance', 'Amplification naturelle d\'un son due à la vibration d\'un objet ou d\'une cavité.', NULL, NULL),
('vibration', 'Mouvement oscillatoire qui produit un son.', NULL, NULL),
('fréquence', 'Nombre de vibrations par seconde d\'un son, mesuré en hertz (Hz).', NULL, NULL),
('hauteur', 'Caractéristique d\'un son qui permet de le classer comme grave ou aigu, déterminée par la fréquence.', NULL, NULL),
('ultrason', 'Son dont la fréquence est trop élevée pour être perçue par l\'oreille humaine (au-dessus de 20 000 Hz).', NULL, NULL),
('son', 'Vibration acoustique perçue par l\'oreille.', NULL, NULL),
('synthèse sonore', 'Création de sons artificiels en manipulant des ondes sonores, des harmoniques et des enveloppes.', NULL, NULL),
('son de synthèse', 'Son généré électroniquement, souvent à l\'aide de synthétiseurs.', NULL, NULL),
('mixage', 'Processus de combinaison et d\'équilibrage des pistes sonores pour créer une version finale.', NULL, NULL),
('panoramique', 'Répartition du son entre les canaux gauche et droit dans un mixage stéréo.', NULL, NULL),
('espace', 'Répartition des sons dans un environnement acoustique ou dans un mixage.', NULL, NULL),
('strate', 'Couche sonore dans une composition (mélodie, harmonie, rythme).', NULL, NULL),
('sourdine', 'Dispositif utilisé pour atténuer le son d\'un instrument, modifiant son timbre.', NULL, NULL),
('effet', 'Modification du son pour créer une ambiance ou une texture particulière.', NULL, NULL),
('distorsion', 'Altération du signal sonore pour créer un effet de saturation.', NULL, NULL),
('rétrograde', 'Technique où une mélodie ou un motif est joué à l\'envers.', NULL, NULL),
('stéréo', 'Technique de diffusion sonore utilisant deux canaux (gauche et droit) pour créer une impression d\'espace.', NULL, NULL),
('réverbération', 'Persistence du son après sa production, due à la réflexion des ondes dans un espace.', NULL, NULL),
('écho', 'Répétition d\'un son due à la réflexion des ondes sonores sur une surface.', NULL, NULL),
('filtrage', 'Processus de modification du spectre sonore en atténuant ou en amplifiant certaines fréquences.', NULL, NULL),
('arrangement', 'Adaptation d\'une œuvre musicale pour un ensemble différent de l\'original.', NULL, NULL),
('basse continue', 'Technique d\'accompagnement baroque utilisant une ligne de basse enrichie d\'accords improvisés.', NULL, NULL),
('instrumentation', 'Art de choisir et de combiner les instruments pour une composition.', NULL, NULL),
('orchestration', 'Art d\'arranger une composition pour un orchestre.', NULL, NULL),
('réduction', 'Arrangement d\'une œuvre orchestrale pour un ensemble plus petit, souvent pour piano.', NULL, NULL),
('transcription', 'Adaptation d\'une œuvre musicale pour un instrument ou un ensemble différent.', NULL, NULL);